# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :upload_testflight do

	match(
	  app_identifier: "delight010.savemymoney",
	  readonly: true
	)
	
	app_store_connect_api_key(
	  key_id: ENV['APP_STORE_CONNECT_KEY_ID'],
	  issuer_id: ENV['APP_STORE_CONNECT_ISSUER_ID'],
	  key_filepath: ENV['APP_STORE_CONNECT_API']
	)

	build_app(
	  scheme: "SaveMyMoney",
	  configuration: "Release",
	  clean: true,
    	  xcargs: "-allowProvisioningUpdates -verbose",
	  export_method: "app-store",
	  export_options: {
	    signingStyle: "manual",
	    method: "app-store",
	    provisioningProfiles: { 
               "delight010.savemymoney" => "match Development delight010.savemymoney"
            }
          }
	)

	upload_to_testflight(
	  distribute_external: true
	)
    # add actions here: https://docs.fastlane.tools/actions
  end
end
